[server]
port = 7568
fileWatcherType = "auto"
headless = true
runOnSave = true

[theme]
primaryColor = "#d33682"
backgroundColor = "#002b36"
secondaryBackgroundColor = "#586e75"
textColor = "#fafafa"
font = "sans serif"
